spring:
  datasource:
    url: "jdbc:mariadb://localhost/library"
    username: "root"
    password: "0126"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect